# Generated by Django 4.1.7 on 2023-06-17 20:22

from django.db import migrations, models
import loan.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanFields',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED'), (2, 'REJECTED')], default=loan.models.LoanStatus['PENDING'])),
            ],
        ),
    ]
