# Generated by Django 4.1.7 on 2023-06-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanFields',
            new_name='LoanField',
        ),
    ]
