# Generated by Django 4.1.7 on 2023-06-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_rename_loanfields_loanfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanoffer',
            name='answered_fields',
            field=models.JSONField(default=dict),
        ),
    ]
